#!/usr/bin/env node
// Single source of truth: repo-root VERSION file.
// - Generates swyft/Sources/swyft/Version.swift (git-ignored, build artifact).
// - Asserts package.json version matches VERSION (fails build on drift).

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const version = readFileSync(join(root, "VERSION"), "utf8").trim();
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`gen-version: VERSION "${version}" is not semver x.y.z`);
  process.exit(1);
}

// Bump this only on breaking stdio/NDJSON contract changes.
const PROTOCOL = 1;

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
if (pkg.version !== version) {
  console.error(
    `gen-version: package.json version (${pkg.version}) != VERSION (${version}).\n` +
      `Update both together (VERSION is source of truth).`,
  );
  process.exit(1);
}

const swift = `// Generated by scripts/gen-version.mjs from repo-root VERSION. Do not edit.
let swyftVersion = "${version}"
let swyftProtocol = ${PROTOCOL}
`;
writeFileSync(join(root, "swyft/Sources/swyft/Version.swift"), swift);

console.log(`gen-version: ${version} (protocol ${PROTOCOL})`);
