#!/usr/bin/env node
// Single source of truth: package.json "version".
// Generates swyft/Sources/swyft/Version.swift (git-ignored build artifact) so
// the binary's `swyft version` matches the extension.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = String(pkg.version).trim();
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`gen-version: package.json version "${version}" is not semver x.y.z`);
  process.exit(1);
}

// Bump this only on breaking stdio/NDJSON contract changes.
const PROTOCOL = 1;

const swift = `// Generated by scripts/gen-version.mjs from package.json. Do not edit.
let swyftVersion = "${version}"
let swyftProtocol = ${PROTOCOL}
`;
writeFileSync(join(root, "swyft/Sources/swyft/Version.swift"), swift);

console.log(`gen-version: ${version} (protocol ${PROTOCOL})`);
